### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by robertandrews** [nekoshita/obsidian-auto-card-link#10]
Two methods tried:

**1. Folder addition.**

I downloaded the .zip from here, unzipped to Obsidian's plugins folder.

Top-right of the main window shows: `Failed to install plugin`

Console shows:

```
Plugin failure: auto-card-link Error: ENOENT: no such file or directory, open '/Users/robert/Library/Mobile Documents/iCloud~md~obsidian/Documents/My vault/.obsidian/plugins/obsidian-auto-card-link/main.js'
```

**2. Install via BRAT.**

BRAT reports:

<img width="331" alt="Screenshot 2022-04-15 at 19 48 28" src="https://user-images.githubusercontent.com/3158787/163613632-4b6b5358-fd3d-4d8c-9385-fe8326cefd49.png">

**Comment by nekoshita** [comment]
@robertandrews  Thanks for trying!
BRAT installation failed because version number had `v` prefix.
I fixed it, I installed via BRAT and it worked successfully!
Please try installing this plugin via BRAT again and see if it works, thanks!

**Comment by robertandrews** [comment]
Works now, thanks!

Very interesting. Coming from Notion, this link presentation feels familiar and comforting.

Though, in the sense that Obsidian presents itself as plain-text, future-proof etc, there's a lot of code used to make the `cardlink` which is fairly custom. Could you just convert standard Markdown links on-the-fly by fetching the destination page meta data? Maybe with the addition of a single parameter to differentiate from links that are to be left as non-cards.

Then the standard link format would be left in place for the future...

I guess the need for this to function offline would nix that? ie. it would need to make remote calls for each destination page?

**Comment by nekoshita** [comment]
@robertandrews 
Thanks for trying and giving me feedbacks!

> Could you just convert standard Markdown links on-the-fly by fetching the destination page meta data?

I love the idea and I would do that if possible!  But, I don't think we can do that  because you can't change the way how plain-texts are displayed. The only ways to change it is to use HTML tags or code blocks...

**Comment by robertandrews** [comment]
Ah, I guess, from my point of view is two things... i) Obsidian newbie, TBH and ii) using the hybrid Live View/Edit View. I was speculating that there may be a way to render it in Live View, if not in Edit.

**Comment by nekoshita** [comment]
Thank you again for your valuable feedback!
I'm closing this issue since installation problem has solved.
