### ISSUE TITLE
Thank you note

### ISSUE THREAD

**Issue by Welding-Torch** [nekoshita/obsidian-auto-card-link#16]
Thank you for making this. I've wished for something like this in Obsidian since the day I started using it over a year ago. Now I have finally found something that satisfies this want. My links look really good, and I'd just like to thank @nekoshita for making this amazing plug-in.

**Comment by nekoshita** [comment]
Thank you for using this plugin!
If there are any additional features you would like, please feel free to create issues, thanks!
