### ISSUE TITLE
How to copy?

### ISSUE THREAD

**Issue by berot3** [nekoshita/obsidian-auto-card-link#25]
Hi,When in reader mode I don't see a way to copy the url.
I can only right-click on the text and copy the text, but without the url.

I have to go to edit mode and go within the Cardlink-block-code to be able to copy the url.

It would be great I think if one could either press right-click and copy url or maybe a hover-button appears like for code-blocks where I can press copy.

**Comment by nekoshita** [comment]
thanks for the PR!
release it as v1.2.1
