### ISSUE TITLE
[Feature Request] Allow using local image for `image` field

### ISSUE THREAD

**Issue by ASVc6** [nekoshita/obsidian-auto-card-link#28]
I tried relative path or `file:///` syntax on Windows but it doesn't work. E.g. `image: file:///D:/book123.jpg`. Favicons also don't display.

There are 2 reasons this feature or improvement would be useful:
- With local images, content would load faster if the note has many links
- Many times (e.g. with links to an Amazon book) the plugin can't get the image even though it can get the title, description, favicon, etc. Would be nice to be able to save any image from the site locally and point `image` field to it. 

Related improvement: an option to automatically save the image and the plugin will use that local one.

**Comment by nekoshita** [comment]
@ormai thanks for adding this feature
Release it as v1.2.2!
