### ISSUE TITLE
Line wrap and card height causing content to get cut off

### ISSUE THREAD

**Issue by JoostScheffer** [nekoshita/obsidian-auto-card-link#29]
When the width of a pane is decreased it causes line wrapping inside the card. This sometimes causes content to get cut off, which is something I find undesirable. 

# Examples:
- When the width of a "pane" exceeds the width of the content a card displays normally (no line wrapping) ![image](https://user-images.githubusercontent.com/56606926/184662376-cc4a579a-259e-40d4-a6fb-59855e2c4767.png)
- A small amount of line wrapping, here only the word "by" is wrapped ![image](https://user-images.githubusercontent.com/56606926/184662654-9d169d04-825f-4fa9-8102-05581c386baa.png)
- Here line wrapping is causing the content to extend beyond the boundaries of the card. The title, Github logo and name of the site are partially cut off.  
![image](https://user-images.githubusercontent.com/56606926/184662823-90b7b3b2-2538-4b83-8bf1-9b37aaaaca88.png)
- Here line wrapping does not cause the elements to move any further. Content that exceeds the line count is replaced with an Ellipsis (`…`)
![image](https://user-images.githubusercontent.com/56606926/184663273-df0138e0-ff93-4175-9cd2-2dbd826c3bad.png)

# My opinion 
To me it would seem nice if none of the content were to get cut off because of line-wrapping. I would suggest starting the usage of the Ellipsis before content would get cut off.

# Environment:
I am using the regular dark theme, on Linux (Plasma 5) with Obsidian for Linux. The screenshots above were made in preview mode.
I included `+`-symbols in the screenshots for reference.

**Comment by JoostScheffer** [comment]
I also just noticed that content also gets cut off when the "description" is too long.
Example:
![image](https://user-images.githubusercontent.com/56606926/184686165-deffcea9-3413-473d-9033-c3a61624a8dd.png)

**Comment by helicos6** [comment]
I also noticed this issue. Strangely, modifying the styles.css file ( vault/.obsidian/plugins/auto-card-link/styles.css ) does not seem to have any effect on the Card style.

![image](https://user-images.githubusercontent.com/34452093/208357116-a83d4eeb-fb62-45cf-9093-784c23106437.png)

**Comment by curiosity654** [comment]
Same problem here

**Comment by shayded-exe** [comment]
Also experiencing this. It's especially an issue with an increased font size. Setting the card height with `em` instead of `px` should fix this.

![image](https://user-images.githubusercontent.com/1417838/210416721-a286a4d1-e1f0-4e6d-aece-4f13cb3e9c95.png)

**Comment by LukasManinger** [comment]
I solved this problem by using a CSS snippet ("Options" → "Appearance" → "CSS snippets"). Simply put a `.css` file with the following content into your snippets folder:

```css
.auto-card-link-card {
    height: 9em;
}

.auto-card-link-thumbnail {
    height: 100%;
    max-width: 40%;
}
```

This should ensure that card links work independent of font size. However, which exact values you use is a matter of personal preference.

**Comment by nekoshita** [comment]
thanks for the PR!
release it as v1.2.1
