### ISSUE TITLE
Made a fork

### ISSUE THREAD

**Issue by ormai** [nekoshita/obsidian-auto-card-link#37]
Hi everyone. I don't know if there is still someone interested in this plugin, since this repository seems dead, but I like it, so I fixed some issues and added some features.

My changes are **[here](https://github.com/ormai/obsidian-card-links)**. The plugin can be only [installed manually](https://github.com/ormai/obsidian-card-links#manual-installation) for now.

What I changed:

- relative path for fetched images is no longer a problem ([#36](https://github.com/nekoshita/obsidian-auto-card-link/issues/36))
- updated the overall appearance and layout of the card, it now uses Obsidian's css variables
- now text wraps and truncates properly ([#29](https://github.com/nekoshita/obsidian-auto-card-link/issues/29))
- added a nice button to copy the URL from preview and live-preview mode ([#25](https://github.com/nekoshita/obsidian-auto-card-link/issues/25))
- there is now the possibility to turn off (form settings) the fetching of some non-required fields (description, favicon, host, thumbnail)
- it is now possible to (optionally) store all images locally ([#28](https://github.com/nekoshita/obsidian-auto-card-link/issues/28) more or less)

@nekoshita I really like your work on this plugin. Let me know if you are willing to integrate my changes in here.

---

## Edit

After I discovered that this repository is not dead I deleted the fork and introduced my changes here.

**Comment by xhuajin** [comment]
Hello, I like this plugin very much so i'm looking for ways to make this plugin call to local images. Knowing that you had fixed those problems and added some features, but it seems the lins is unused. Wondering if there was a chance to experience the plugins you made. Thank you very much for reading my letter and thank you very much for trying to solve these problems.

**Comment by ormai** [comment]
Hi!
What I did was adding an option to download each image to to the plugin directory. This doesn't speed up loading very much (maybe it does on slow networks though) and there is already some sort of caching done by Electron probably.

Using local images in the yaml code block is not possible as of now because Obsidian uses ad hoc links.

![image](https://github.com/nekoshita/obsidian-auto-card-link/assets/81334289/1997a660-c812-4e14-8115-2f3c0b4ba047)

Support for this could be possible through [DataAdapter.getResourcePath()](https://docs.obsidian.md/Reference/TypeScript+API/DataAdapter/getResourcePath).

I see if I can get something working.

**Comment by xhuajin** [comment]
I'm glad you got back to me so quickly. I may not be able to help you at my current level, but thank you very much for your answer and for your willingness to keep trying. I'll wait for your good news. Good luck!!!
