### ISSUE TITLE
[Bug] Enabling Minimal Theme Setting deforms the cards.

### ISSUE THREAD

**Issue by albertoloscerritos** [nekoshita/obsidian-auto-card-link#49]
When using minimal Theme, if I activate the minimal theme settings plugins, the cards will be deformed...

![auto-card-bug-2](https://github.com/nekoshita/obsidian-auto-card-link/assets/16707033/41d55479-5c93-4970-9162-a694456791ee)

I'm using obsidian 1.4.12
Thanks

**Comment by ormai** [comment]
@albertoloscerritos Thank you for reporting this.

**Comment by nekoshita** [comment]
@ormai Thank you for fixing this bug.
Release it as v1.2.2!
