### ISSUE TITLE
This link fails

### ISSUE THREAD

**Issue by gerroon** [nekoshita/obsidian-auto-card-link#58]
`https://www.youtube.com/@FinePointCGI/videos`

![image](https://github.com/nekoshita/obsidian-auto-card-link/assets/8519469/76931f68-19b7-45ba-8047-29a276084cdf)

**Comment by ormai** [comment]
Hey, thanks for reporting this bug.

The generated cardlink of this link contains the character `\` which triggers this error:

```
YAMLParseError: Invalid escape sequence \p at line 3, column 160:

… channel is used for news on the gaming\programming industry and for tutorials…
```

For now you can try escaping all the single backslashes like `\\`.

**Comment by nekoshita** [comment]
@ormai Thank you for fixing this bug.
Release it as v1.2.3!
