### ISSUE TITLE
[Feature request] Batch processing

### ISSUE THREAD

**Issue by jerefrer** [nekoshita/obsidian-auto-card-link#59]
First of all thanks a lot for this great plugin !

Since it worked so well, when I pasted a bunch of URLs, I tried to select all of them, right-click and "Enhance selected URL to card link" but nothing happened.

Wouldn't it be nice to be able to process a list of URLs instead of having to copy paste them one by one ?

Thanks in advance, have a great weekend :)

**Comment by nekoshita** [comment]
@ormai Thank you for the implementation.
Now it's released as v1.2.3!

**Comment by jerefrer** [comment]
Wonderful, thank you all so much :)
