### ISSUE TITLE
Consider adding a changelog or release notes

### ISSUE THREAD

**Issue by ngirard** [nekoshita/obsidian-auto-card-link#61]
Hey @nekoshita ,

You seem to have added valuable features recently, but it's not quite easy to take advantage of them because the relevant information is buried in the commit history.

Could you please consider adding a changelog or release notes ?

Cheers, and thanks for your work !

**Comment by nekoshita** [comment]
I added release note
https://github.com/nekoshita/obsidian-auto-card-link/releases/tag/1.2.3

**Comment by ngirard** [comment]
Great, thanks !
